version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    postrgesdb:
        image: postgres:12.3
        container_name: postgres
        ports:
        - "5432:5432"
        environment:
            POSTGRES_DATABASE: 'database'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'pg2020'